object Versions {
    const val core = "1.7.0"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val lifeCycle = "2.4.0"
    const val hilt = "2.40"
    const val recyclerView = "1.2.1"
    const val dexter = "6.2.3"
    const val kotlin = "1.5.31"
    const val coroutines = "1.5.2"
    const val okhttp = "4.9.1"
    const val retrofit = "2.9.0"
    const val junit = "4.13.2"
    const val coreTesting = "2.1.0"
    const val mockitoKotlin = "4.0.0"
    const val mockitoInline = "4.0.0"
    const val espresso = "3.4.0"
    const val junitKtx = "1.1.3"
    const val navigation = "2.3.5"
    const val glide = "4.11.0"
}